export const formattedExpectedOutput = [
  "Matchday 1",
  "Capitola Seahorses, 3 pts",
  "Felton Lumberjacks, 3 pts",
  "San Jose Earthquakes, 1 pt",
  null,
  "Matchday 2",
  "Capitola Seahorses, 4 pts",
  "Aptos FC, 3 pts",
  "Felton Lumberjacks, 3 pts",
  null,
  "Matchday 3",
  "Aptos FC, 6 pts",
  "Felton Lumberjacks, 6 pts",
  "Monterey United, 6 pts",
  null,
  "Matchday 4",
  "Aptos FC, 9 pts",
  "Felton Lumberjacks, 7 pts",
  "Monterey United, 6 pts",
];

export const smallLeagueExpectedOutput = [
  "Matchday 1",
  "Real Madrid, 3 pts",
  "Barcelona, 0 pts",
  null,
  "Matchday 2",
  "Real Madrid, 3 pts",
  "Atletico, 1 pt",
  "Barcelona, 1 pt",
  null,
  "Matchday 3",
  "Real Madrid, 6 pts",
  "Atletico, 1 pt",
  "Barcelona, 1 pt",
];

export const unformattedExpectedOutput = [
  "Matchday 1",
  "Capitola Seahorses, 3 pts",
  "San Jose Earthquakes, 1 pt",
  "Santa Cruz Slugs, 1 pt",
  null,
  "Matchday 2",
  "Capitola Seahorses, 4 pts",
  "Aptos FC, 3 pts",
  "San Jose Earthquakes, 2 pts",
  null,
  "Matchday 3",
  "Aptos FC, 6 pts",
  "Capitola Seahorses, 5 pts",
  "San Jose Earthquakes, 2 pts",
];
