name: jane-soccer-challenge-workflow

on:
  push:
    branches: [main]
  pull_request:
    branches: ["*"]

jobs:
  static-analysis:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 16.17.1
      - name: Install Dependencies
        run: yarn install --frozen-lockfile
      - name: Run Linter
        run: yarn lint:ts
      - name: Typecheck
        run: yarn typecheck
  ts-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 16.17.1
      - name: Install Dependencies
        run: yarn install --frozen-lockfile
      - name: Run Tests
        run: yarn test
